FROM golang:latest AS builder

WORKDIR /app

COPY . .

RUN go build -o main .

FROM alpine:latest

RUN apk add libc6-compat && apk --no-cache add ca-certificates

WORKDIR /app/

COPY --from=builder /app/main .

EXPOSE 8080

CMD ["./main"]
